---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        state: present

    - name: Install apt-transport-https
      apt:
        name:
          - apt-transport-https
        state: present
