---
- hosts: k8s-nodes
  become: yes
  vars:
    k8s_version: 1.20.0
  tasks:
    - name: Install dependencies
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

    - name: Install Kubernetes components
      package:
        name: kubelet={{ k8s_version }}-00
        state: present

    - name: Enable and start kubelet service
      service:
        name: kubelet
        enabled: yes
        state: started
